In [107]:
import pandas as pd

In [108]:
data=pd.read_excel(r"E:\pandas\L2G8810_Lidar_KPI_Test_Report_OD_HIL_I480_V3_ER_GER_KAFAS_GT_Part3.xlsx",sheet_name= "False Positives", header=61)

In [109]:
data

,RecordingName,sequenceName,RecogLidarObjectlist_Objectlist_object_list_summary_id,VelocityAndVehicleConditionProvision_velocityVehicle_velocityvehiclecog_velocityvehiclecog,OD_OM_timestamp,DUT_ptp_timestamp,first_occurence,last_occurence,suffix,object_45m,...,DUT_Velocity_y_rel,DUT_Age,DUT_Movement,Priority,Root_cause,Sub_category,Comments,Found Both In Iteration and Base,Found Just In Base,Found Just In Iteration
0,LIDAR_LJ02772_20240118_113255_I480-PDX-009-048...,LIDAR_LJ02772_20240118_113255,3710,0.000000,22603907,1705578513275000,22588508,22603907,last_occurance,False,...,0.071916,1272,0,NaN,DUT error,BB matching static object+20cm,NaN,False,False,True
1,LIDAR_LJ02772_20240118_113255_I480-PDX-009-048...,LIDAR_LJ02772_20240118_113255,5020,0.984375,22719568,1705578628939770,22715368,22719568,last_occurance,False,...,0.010287,494,1,NaN,DUT error,BB matching static object+20cm,NaN,False,False,True
2,LIDAR_LJ02766_20240202_151013_I480-PDX-009-048...,LIDAR_LJ02766_20240202_151013,4190,11.171875,26562043,1706886943601770,26562043,26565710,first_occurance,False,...,0.106134,76,0,NaN,NaN,NaN,NaN,False,False,False
3,LIDAR_LJ02772_20240118_101131_I480-PDX-009-048...,LIDAR_LJ02772_20240118_101131,10,2.500000,17568898,1705573478091370,17568698,17568898,last_occurance,False,...,-0.008196,691,0,NaN,GT error,GT object of incorrect dimensions,NaN,False,False,True
4,LIDAR_LJ02772_20240118_121322_I480-PDX-009-048...,LIDAR_LJ02772_20240118_121322,3850,21.734375,24602801,1705580512239900,24602201,24602801,last_occurance,False,...,0.241823,2066,0,NaN,Data error,Out of ODD (Insufficient pre-label details),Lane change,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,LIDAR_LJ02772_20240118_115309_I480-PDX-009-048...,LIDAR_LJ02772_20240118_115309,2990,4.359375,22984621,1705578894001980,22984287,22984621,last_occurance,False,...,-0.033994,250,255,NaN,DUT error,BB matching static object+20cm,NaN,False,False,True
98,LIDAR_LJ02772_20240118_134101_I480-PDX-009-048...,LIDAR_LJ02772_20240118_134101,550160,4.765625,30009977,1705585919602540,30009977,30014844,first_occurance,False,...,-0.011104,275,0,NaN,NaN,NaN,NaN,False,False,False
99,LIDAR_LJ02772_20240118_093104_I480-PDX-009-048...,LIDAR_LJ02772_20240118_093104,2710,0.000000,14876301,1705570785407690,14876301,14876301,first_occurance,False,...,1.340098,15,0,NaN,NaN,NaN,NaN,False,False,False
100,LIDAR_LJ02772_20240118_093104_I480-PDX-009-048...,LIDAR_LJ02772_20240118_093104,2710,0.000000,14876301,1705570785407690,14876301,14876301,last_occurance,False,...,1.340098,15,0,NaN,NaN,NaN,NaN,False,False,True
101,LIDAR_LJ02772_20240118_134101_I480-PDX-009-048...,LIDAR_LJ02772_20240118_134101,3140110,11.796875,29969979,1705585879603230,29968046,29969979,last_occurance,False,...,0.001674,227,0,NaN,Data error,FP due to Overtaken object of Low Visibility,NaN,False,False,True

In [110]:
data[["sequenceName"]]

                      sequenceName
0    LIDAR_LJ02772_20240118_113255
1    LIDAR_LJ02772_20240118_113255
2    LIDAR_LJ02766_20240202_151013
3    LIDAR_LJ02772_20240118_101131
4    LIDAR_LJ02772_20240118_121322
..                             ...
97   LIDAR_LJ02772_20240118_115309
98   LIDAR_LJ02772_20240118_134101
99   LIDAR_LJ02772_20240118_093104
100  LIDAR_LJ02772_20240118_093104
101  LIDAR_LJ02772_20240118_134101

[102 rows x 1 columns]

In [111]:
data.isna().sum()

RecordingName                                                                                   0
sequenceName                                                                                    0
RecogLidarObjectlist_Objectlist_object_list_summary_id                                          0
VelocityAndVehicleConditionProvision_velocityVehicle_velocityvehiclecog_velocityvehiclecog      0
OD_OM_timestamp                                                                                 0
                                                                                             ...
Sub_category                                                                                   78
Comments                                                                                      101
Found Both In Iteration and Base                                                                0
Found Just In Base                                                                              0
Found Just In Iteration                                                                         0
Length: 141, dtype: int64

In [112]:
data.isna()

,RecordingName,sequenceName,RecogLidarObjectlist_Objectlist_object_list_summary_id,VelocityAndVehicleConditionProvision_velocityVehicle_velocityvehiclecog_velocityvehiclecog,OD_OM_timestamp,DUT_ptp_timestamp,first_occurence,last_occurence,suffix,object_45m,...,DUT_Velocity_y_rel,DUT_Age,DUT_Movement,Priority,Root_cause,Sub_category,Comments,Found Both In Iteration and Base,Found Just In Base,Found Just In Iteration
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,True,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
97,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False
98,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,True,False,False,False
99,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,True,False,False,False
100,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,True,True,True,False,False,False
101,False,False,False,False,False,False,False,False,False,False,...,False,False,False,True,False,False,True,False,False,False

In [113]:
data['Root_cause'].isna().sum()

78

In [114]:
data['sequenceName'].dtypes

dtype('O')

In [115]:
df2=data[["DUT_Movement","DUT_Age","Root_cause","Sub_category","OD_OM_timestamp","sequenceName"]]

In [116]:
df2

,DUT_Movement,DUT_Age,Root_cause,Sub_category,OD_OM_timestamp,sequenceName
0,0,1272,DUT error,BB matching static object+20cm,22603907,LIDAR_LJ02772_20240118_113255
1,1,494,DUT error,BB matching static object+20cm,22719568,LIDAR_LJ02772_20240118_113255
2,0,76,NaN,NaN,26562043,LIDAR_LJ02766_20240202_151013
3,0,691,GT error,GT object of incorrect dimensions,17568898,LIDAR_LJ02772_20240118_101131
4,0,2066,Data error,Out of ODD (Insufficient pre-label details),24602801,LIDAR_LJ02772_20240118_121322
...,...,...,...,...,...,...
97,255,250,DUT error,BB matching static object+20cm,22984621,LIDAR_LJ02772_20240118_115309
98,0,275,NaN,NaN,30009977,LIDAR_LJ02772_20240118_134101
99,0,15,NaN,NaN,14876301,LIDAR_LJ02772_20240118_093104
100,0,15,NaN,NaN,14876301,LIDAR_LJ02772_20240118_093104
101,0,227,Data error,FP due to Overtaken object of Low Visibility,29969979,LIDAR_LJ02772_20240118_134101

In [117]:
df2['Root_cause'].isna()

0      False
1      False
2       True
3      False
4      False
       ...
97     False
98      True
99      True
100     True
101    False
Name: Root_cause, Length: 102, dtype: bool

In [118]:
df2['Root_cause'].isna().sum()

78

In [119]:
df2['Root_cause'].fillna('No Error',inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15464\1576915410.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df2['Root_cause'].fillna('No Error',inplace=True)
C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15464\1576915410.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2['Root_cause'].fillna('No Error',inplace=True)

In [120]:
df2

,DUT_Movement,DUT_Age,Root_cause,Sub_category,OD_OM_timestamp,sequenceName
0,0,1272,DUT error,BB matching static object+20cm,22603907,LIDAR_LJ02772_20240118_113255
1,1,494,DUT error,BB matching static object+20cm,22719568,LIDAR_LJ02772_20240118_113255
2,0,76,No Error,NaN,26562043,LIDAR_LJ02766_20240202_151013
3,0,691,GT error,GT object of incorrect dimensions,17568898,LIDAR_LJ02772_20240118_101131
4,0,2066,Data error,Out of ODD (Insufficient pre-label details),24602801,LIDAR_LJ02772_20240118_121322
...,...,...,...,...,...,...
97,255,250,DUT error,BB matching static object+20cm,22984621,LIDAR_LJ02772_20240118_115309
98,0,275,No Error,NaN,30009977,LIDAR_LJ02772_20240118_134101
99,0,15,No Error,NaN,14876301,LIDAR_LJ02772_20240118_093104
100,0,15,No Error,NaN,14876301,LIDAR_LJ02772_20240118_093104
101,0,227,Data error,FP due to Overtaken object of Low Visibility,29969979,LIDAR_LJ02772_20240118_134101

In [121]:
df2.dropna(inplace=True)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15464\1761232742.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2.dropna(inplace=True)

In [122]:
df2

,DUT_Movement,DUT_Age,Root_cause,Sub_category,OD_OM_timestamp,sequenceName
0,0,1272,DUT error,BB matching static object+20cm,22603907,LIDAR_LJ02772_20240118_113255
1,1,494,DUT error,BB matching static object+20cm,22719568,LIDAR_LJ02772_20240118_113255
3,0,691,GT error,GT object of incorrect dimensions,17568898,LIDAR_LJ02772_20240118_101131
4,0,2066,Data error,Out of ODD (Insufficient pre-label details),24602801,LIDAR_LJ02772_20240118_121322
8,255,373,DUT error,BB matching static object+20cm,22918491,LIDAR_LJ02772_20240118_115309
12,0,131,Data error,FP due to Overtaken object of Low Visibility,26565710,LIDAR_LJ02766_20240202_151013
17,0,51,DUT error,BB matching static object+20cm,24243020,LIDAR_LJ02772_20240118_121322
20,0,139,Data error,FP due to Overtaken object of Low Visibility,23225475,LIDAR_LJ02772_20240118_115309
27,0,2955,Data error,Out of ODD (Insufficient pre-label details),16637679,LIDAR_LJ02772_20240118_095116
28,0,2955,Data error,Out of ODD (Insufficient pre-label details),16637679,LIDAR_LJ02772_20240118_095116
29,0,6488,DUT error,Due to Wet road/Water spray,22459115,LIDAR_LJ02772_20240118_113255
31,0,666,DUT error,BB matching static object+20cm,20935224,LIDAR_LJ02766_20240202_133913
38,0,297,DUT error,BB matching static object+20cm,20998220,LIDAR_LJ02766_20240202_133913
46,1,143,DUT error,BB matching static object+20cm,23219742,LIDAR_LJ02772_20240118_115309
47,0,49,Data error,FP due to Overtaken object of Low Visibility,23134809,LIDAR_LJ02766_20240202_141520
49,255,282,DUT error,BB matching static object+20cm,22943290,LIDAR_LJ02772_20240118_115309
50,1,122,GT error,GT object of incorrect dimensions,16644145,LIDAR_LJ02772_20240118_095116
53,1,122,GT error,GT object of incorrect dimensions,16644145,LIDAR_LJ02772_20240118_095116
57,0,1318,DUT error,BB matching static object+20cm,23833575,LIDAR_LJ02772_20240118_115309
59,0,348,Data error,FP due to Overtaken object of Low Visibility,30014844,LIDAR_LJ02772_20240118_134101
63,0,69,DUT error,BB matching static object+20cm,24334215,LIDAR_LJ02772_20240118_121322
80,255,84,DUT error,BB matching static object+20cm,24386146,LIDAR_LJ02772_20240118_121322
97,255,250,DUT error,BB matching static object+20cm,22984621,LIDAR_LJ02772_20240118_115309
101,0,227,Data error,FP due to Overtaken object of Low Visibility,29969979,LIDAR_LJ02772_20240118_134101

In [123]:
df2.size

144

In [124]:
df2.shape

(24, 6)

In [125]:
df2["DUT_Age"].mean()

899.6666666666666

In [126]:
df2["DUT_Age"].median()

289.5

In [127]:
df2["DUT_Age"].mode()[0]

122

In [128]:
df2["Root_cause"].unique()

array(['DUT error', 'GT error', 'Data error'], dtype=object)

In [129]:
df2["Root_cause"].unique()

array(['DUT error', 'GT error', 'Data error'], dtype=object)

In [130]:
df2["Root_cause"].value_counts()

Root_cause
DUT error     13
Data error     8
GT error       3
Name: count, dtype: int64

In [132]:
a = df2['Sub_category'] == 'Out of ODD (Insufficient pre-label details)'
b = df2['Sub_category'] == 'FP due to Overtaken object of Low Visibility'

df2[a | b]

,DUT_Movement,DUT_Age,Root_cause,Sub_category,OD_OM_timestamp,sequenceName
4,0,2066,Data error,Out of ODD (Insufficient pre-label details),24602801,LIDAR_LJ02772_20240118_121322
12,0,131,Data error,FP due to Overtaken object of Low Visibility,26565710,LIDAR_LJ02766_20240202_151013
20,0,139,Data error,FP due to Overtaken object of Low Visibility,23225475,LIDAR_LJ02772_20240118_115309
27,0,2955,Data error,Out of ODD (Insufficient pre-label details),16637679,LIDAR_LJ02772_20240118_095116
28,0,2955,Data error,Out of ODD (Insufficient pre-label details),16637679,LIDAR_LJ02772_20240118_095116
47,0,49,Data error,FP due to Overtaken object of Low Visibility,23134809,LIDAR_LJ02766_20240202_141520
59,0,348,Data error,FP due to Overtaken object of Low Visibility,30014844,LIDAR_LJ02772_20240118_134101
101,0,227,Data error,FP due to Overtaken object of Low Visibility,29969979,LIDAR_LJ02772_20240118_134101